package utilities;

public enum EnvironmentVariables {
    BROWSER,
    BASE_URL,
    LANGUAGE,
    IMPLICIT_WAIT,
    ADMIN_EMAIL,
    BO_EMAIL,
    FD_EMAIL,
    BASIC_USER_EMAIL,
    BO_NO_RESTAURANTS_EMAIL,
    FD_NO_RESTAURANTS_AND_REVIEWS_EMAIL,
    BASIC_WITH_AVATAR_EMAIL,
    COMMON_PASSWORD
}
